- name: nginx server
  apt: pkg=nginx state=latest

- name: no nginx default config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Nginx Running
  service: "name=nginx state=started enabled=yes"
  ignore_errors: true