
- name: "Install Packages (APT)"
  when: ansible_pkg_mgr == "apt"
  apt: "pkg={{item}} state=present"
  with_items:
    - vim
    - git
    - mercurial
    - curl
    - inotify-tools
    - build-essential
    - pkg-config

- name: "Install Packages (PACMAN)"
  when: ansible_pkg_mgr == "pacman"
  pacman: "name={{item}} state=present"
  with_items:
    #- vim
    - git
    - mercurial
    - curl
    - inotify-tools

- npm: name=coffee-script global=yes
- npm: name=coffee-react global=yes
- npm: name=grunt-cli global=yes
- npm: name=less global=yes
- npm: name=requirejs global=yes
- npm: name=yamljs global=yes version=0.1.6
- npm: name=typescript global=yes

