
- name: "Install Packages (APT)"
  when: ansible_pkg_mgr == "apt"
  apt: "pkg={{item}} state=present"
  with_items:
    - vim
    - git
    - mercurial
    - curl
    - inotify-tools
    - build-essential
    - pkg-config
