
- name: "GUI Packages (APT)"
  when: ansible_pkg_mgr == "apt"
  apt: "pkg={{item}} state=present"
  with_items:
    - vim-gtk
    - gitg
    - kdiff3
    - meld
    - tortoisehg
    - gtk2-engines-murrine 
    - gtk2-engines-pixbuf

# MISSING: Tortoisehg

- name: "GUI Packages (PACMAN)"
  when: ansible_pkg_mgr == "pacman"
  pacman: "name={{item}} state=present"
  with_items:
    - gvim
    - gitg
    - kdiff3
    - meld
    - gtk-engine-murrine
    - gdk-pixbuf2
