
#- name: "Mercurial"
#  apt: pkg=mercurial state=present

#- name: "Go Source"
#  hg: repo="https://code.google.com/p/go" revision=release dest=/opt/go
#  notify: purge-go-repo

#- name: "Install Go"
#  shell: ./all.bash chdir=/opt/go/src/ creates=/opt/go/pkg

- name: "Download golang archive"
  get_url: url=https://storage.googleapis.com/golang/go1.3.2.linux-amd64.tar.gz dest=/opt/src

- name: "Unarchive Go (raw)"
  unarchive: copy=no src=/opt/src/go1.3.2.linux-amd64.tar.gz dest=/opt/

- template: dest=/etc/profile.d/go.sh src=profile.sh
