- name: "/opt/pkg directory"
  file: path=/opt/pkg state=directory mode=770

- name: "Download golang archive"
  get_url: url=https://storage.googleapis.com/golang/go1.3.3.linux-amd64.tar.gz dest=/opt/pkg/go1.3.3.linux-amd64.tar.gz

- name: "Unarchive Go (raw)"
  unarchive: copy=no src=/opt/pkg/go1.3.3.linux-amd64.tar.gz dest=/opt/

- template: dest=/etc/profile.d/go.sh src=profile.sh
