# Due to oracle's licensing thing, you will need to
# prepare (or ask for) the .tgz files.
#
# http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase6-419409.html
# The downloads are bin files, you will need to run the bin, 
# rename the folder it creates (e.g. 'jdk6-32', 'jre7-64'),
# then tar (e.g. 'tar -cvzf jre6-32.tgz jre6-32.tgz')
#
# ... sorry.

- name: "dpkg --add-architecture i386"
  command: dpkg --add-architecture i386
  when: java_versions|join|search("-32") and ansible_os_family=="Debian"
#and dpkg --print-foreign-architectures doesn't contain i386

- name: "32 bit supporting libraries"
  apt: pkg="{{item}}"
  with_items:
    - "libc6-i386"
    - "lib32stdc++6"
    - "lib32gcc1"
    - "lib32ncurses5"
    - "lib32z1"
  when: java_versions|join|search("-32") and ansible_os_family=="Debian"

- name: "/opt/java"
  file: path=/opt/java state=directory mode=0775 owner=root group=root

- name: "unarchive versions"
  unarchive:
    src: "{{item}}.tgz"
    dest: /opt/java
    creates: "/opt/java/{{item}}"
  with_items: java_versions


